name: Update Counter Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 AM UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python update_counter.py

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        git config user.name "Eric Tech"
        git config user.email "erictech.et@gmail.com"

        git add counter.txt
        git diff --cached --quiet || git commit -m "Automated counter update"

        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref_name }}
