name: Update Counter Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 AM UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll set credentials manually

      - name: Set up GitHub credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ettechh/counter-bot.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_counter.py
